// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/pkg/grpc/proto/metraly.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IngestRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *IngestRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{2}
}

type OverviewMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrsOpened     int32                  `protobuf:"varint,1,opt,name=prs_opened,json=prsOpened,proto3" json:"prs_opened,omitempty"`
	TasksBlocked  int32                  `protobuf:"varint,2,opt,name=tasks_blocked,json=tasksBlocked,proto3" json:"tasks_blocked,omitempty"`
	CiFailures    int32                  `protobuf:"varint,3,opt,name=ci_failures,json=ciFailures,proto3" json:"ci_failures,omitempty"`
	PrsMerged     int32                  `protobuf:"varint,4,opt,name=prs_merged,json=prsMerged,proto3" json:"prs_merged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewMetrics) Reset() {
	*x = OverviewMetrics{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewMetrics) ProtoMessage() {}

func (x *OverviewMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewMetrics.ProtoReflect.Descriptor instead.
func (*OverviewMetrics) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{3}
}

func (x *OverviewMetrics) GetPrsOpened() int32 {
	if x != nil {
		return x.PrsOpened
	}
	return 0
}

func (x *OverviewMetrics) GetTasksBlocked() int32 {
	if x != nil {
		return x.TasksBlocked
	}
	return 0
}

func (x *OverviewMetrics) GetCiFailures() int32 {
	if x != nil {
		return x.CiFailures
	}
	return 0
}

func (x *OverviewMetrics) GetPrsMerged() int32 {
	if x != nil {
		return x.PrsMerged
	}
	return 0
}

type ActivityItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityItem) Reset() {
	*x = ActivityItem{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityItem) ProtoMessage() {}

func (x *ActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityItem.ProtoReflect.Descriptor instead.
func (*ActivityItem) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ActivityItem) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ActivityItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTeam) Reset() {
	*x = TopTeam{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTeam) ProtoMessage() {}

func (x *TopTeam) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTeam.ProtoReflect.Descriptor instead.
func (*TopTeam) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{5}
}

func (x *TopTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TopTeam) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *TopTeam) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HourlyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          string                 `protobuf:"bytes,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourlyStats) Reset() {
	*x = HourlyStats{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyStats) ProtoMessage() {}

func (x *HourlyStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyStats.ProtoReflect.Descriptor instead.
func (*HourlyStats) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{6}
}

func (x *HourlyStats) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *HourlyStats) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopAuthor) Reset() {
	*x = TopAuthor{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopAuthor) ProtoMessage() {}

func (x *TopAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopAuthor.ProtoReflect.Descriptor instead.
func (*TopAuthor) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{7}
}

func (x *TopAuthor) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TopAuthor) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *OverviewMetrics       `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	Activity      []*ActivityItem        `protobuf:"bytes,2,rep,name=activity,proto3" json:"activity,omitempty"`
	TopTeams      []*TopTeam             `protobuf:"bytes,3,rep,name=top_teams,json=topTeams,proto3" json:"top_teams,omitempty"`
	Hourly        []*HourlyStats         `protobuf:"bytes,4,rep,name=hourly,proto3" json:"hourly,omitempty"`
	TopAuthors    []*TopAuthor           `protobuf:"bytes,5,rep,name=top_authors,json=topAuthors,proto3" json:"top_authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{8}
}

func (x *GetDashboardResponse) GetOverview() *OverviewMetrics {
	if x != nil {
		return x.Overview
	}
	return nil
}

func (x *GetDashboardResponse) GetActivity() []*ActivityItem {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *GetDashboardResponse) GetTopTeams() []*TopTeam {
	if x != nil {
		return x.TopTeams
	}
	return nil
}

func (x *GetDashboardResponse) GetHourly() []*HourlyStats {
	if x != nil {
		return x.Hourly
	}
	return nil
}

func (x *GetDashboardResponse) GetTopAuthors() []*TopAuthor {
	if x != nil {
		return x.TopAuthors
	}
	return nil
}

type GetTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsRequest) Reset() {
	*x = GetTeamsRequest{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsRequest) ProtoMessage() {}

func (x *GetTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{9}
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{10}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsResponse) Reset() {
	*x = GetTeamsResponse{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsResponse) ProtoMessage() {}

func (x *GetTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{11}
}

func (x *GetTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{12}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{13}
}

func (x *GetTeamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTeamResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTeamOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamOverviewRequest) Reset() {
	*x = GetTeamOverviewRequest{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamOverviewRequest) ProtoMessage() {}

func (x *GetTeamOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetTeamOverviewRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{14}
}

func (x *GetTeamOverviewRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamOverview struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TeamId             string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	PrsAwaitingReview  int32                  `protobuf:"varint,2,opt,name=prs_awaiting_review,json=prsAwaitingReview,proto3" json:"prs_awaiting_review,omitempty"`
	PrsMerged          int32                  `protobuf:"varint,3,opt,name=prs_merged,json=prsMerged,proto3" json:"prs_merged,omitempty"`
	BlockedTasks       int32                  `protobuf:"varint,4,opt,name=blocked_tasks,json=blockedTasks,proto3" json:"blocked_tasks,omitempty"`
	CiFailuresLastHour int32                  `protobuf:"varint,5,opt,name=ci_failures_last_hour,json=ciFailuresLastHour,proto3" json:"ci_failures_last_hour,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TeamOverview) Reset() {
	*x = TeamOverview{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamOverview) ProtoMessage() {}

func (x *TeamOverview) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamOverview.ProtoReflect.Descriptor instead.
func (*TeamOverview) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{15}
}

func (x *TeamOverview) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamOverview) GetPrsAwaitingReview() int32 {
	if x != nil {
		return x.PrsAwaitingReview
	}
	return 0
}

func (x *TeamOverview) GetPrsMerged() int32 {
	if x != nil {
		return x.PrsMerged
	}
	return 0
}

func (x *TeamOverview) GetBlockedTasks() int32 {
	if x != nil {
		return x.BlockedTasks
	}
	return 0
}

func (x *TeamOverview) GetCiFailuresLastHour() int32 {
	if x != nil {
		return x.CiFailuresLastHour
	}
	return 0
}

type GetTeamOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *TeamOverview          `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamOverviewResponse) Reset() {
	*x = GetTeamOverviewResponse{}
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamOverviewResponse) ProtoMessage() {}

func (x *GetTeamOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_grpc_proto_metraly_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetTeamOverviewResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP(), []int{16}
}

func (x *GetTeamOverviewResponse) GetOverview() *TeamOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

var File_internal_pkg_grpc_proto_metraly_proto protoreflect.FileDescriptor

const file_internal_pkg_grpc_proto_metraly_proto_rawDesc = "" +
	"\n" +
	"%internal/pkg/grpc/proto/metraly.proto\x12\x04grpc\"y\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"G\n" +
	"\x0eIngestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\"\x15\n" +
	"\x13GetDashboardRequest\"\x95\x01\n" +
	"\x0fOverviewMetrics\x12\x1d\n" +
	"\n" +
	"prs_opened\x18\x01 \x01(\x05R\tprsOpened\x12#\n" +
	"\rtasks_blocked\x18\x02 \x01(\x05R\ftasksBlocked\x12\x1f\n" +
	"\vci_failures\x18\x03 \x01(\x05R\n" +
	"ciFailures\x12\x1d\n" +
	"\n" +
	"prs_merged\x18\x04 \x01(\x05R\tprsMerged\"Y\n" +
	"\fActivityItem\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"Y\n" +
	"\aTopTeam\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"7\n" +
	"\vHourlyStats\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\tR\x04hour\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"9\n" +
	"\tTopAuthor\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x82\x02\n" +
	"\x14GetDashboardResponse\x121\n" +
	"\boverview\x18\x01 \x01(\v2\x15.grpc.OverviewMetricsR\boverview\x12.\n" +
	"\bactivity\x18\x02 \x03(\v2\x12.grpc.ActivityItemR\bactivity\x12*\n" +
	"\ttop_teams\x18\x03 \x03(\v2\r.grpc.TopTeamR\btopTeams\x12)\n" +
	"\x06hourly\x18\x04 \x03(\v2\x11.grpc.HourlyStatsR\x06hourly\x120\n" +
	"\vtop_authors\x18\x05 \x03(\v2\x0f.grpc.TopAuthorR\n" +
	"topAuthors\"\x11\n" +
	"\x0fGetTeamsRequest\"*\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x10GetTeamsResponse\x12 \n" +
	"\x05teams\x18\x01 \x03(\v2\n" +
	".grpc.TeamR\x05teams\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"5\n" +
	"\x0fGetTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x16GetTeamOverviewRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\xce\x01\n" +
	"\fTeamOverview\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12.\n" +
	"\x13prs_awaiting_review\x18\x02 \x01(\x05R\x11prsAwaitingReview\x12\x1d\n" +
	"\n" +
	"prs_merged\x18\x03 \x01(\x05R\tprsMerged\x12#\n" +
	"\rblocked_tasks\x18\x04 \x01(\x05R\fblockedTasks\x121\n" +
	"\x15ci_failures_last_hour\x18\x05 \x01(\x05R\x12ciFailuresLastHour\"I\n" +
	"\x17GetTeamOverviewResponse\x12.\n" +
	"\boverview\x18\x01 \x01(\v2\x12.grpc.TeamOverviewR\boverview2\xcd\x02\n" +
	"\fEventService\x123\n" +
	"\x06Ingest\x12\x13.grpc.IngestRequest\x1a\x14.grpc.IngestResponse\x12E\n" +
	"\fGetDashboard\x12\x19.grpc.GetDashboardRequest\x1a\x1a.grpc.GetDashboardResponse\x129\n" +
	"\bGetTeams\x12\x15.grpc.GetTeamsRequest\x1a\x16.grpc.GetTeamsResponse\x126\n" +
	"\aGetTeam\x12\x14.grpc.GetTeamRequest\x1a\x15.grpc.GetTeamResponse\x12N\n" +
	"\x0fGetTeamOverview\x12\x1c.grpc.GetTeamOverviewRequest\x1a\x1d.grpc.GetTeamOverviewResponseB6Z4github.com/getmetraly/metraly/internal/pkg/grpc;grpcb\x06proto3"

var (
	file_internal_pkg_grpc_proto_metraly_proto_rawDescOnce sync.Once
	file_internal_pkg_grpc_proto_metraly_proto_rawDescData []byte
)

func file_internal_pkg_grpc_proto_metraly_proto_rawDescGZIP() []byte {
	file_internal_pkg_grpc_proto_metraly_proto_rawDescOnce.Do(func() {
		file_internal_pkg_grpc_proto_metraly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_grpc_proto_metraly_proto_rawDesc), len(file_internal_pkg_grpc_proto_metraly_proto_rawDesc)))
	})
	return file_internal_pkg_grpc_proto_metraly_proto_rawDescData
}

var file_internal_pkg_grpc_proto_metraly_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_pkg_grpc_proto_metraly_proto_goTypes = []any{
	(*IngestRequest)(nil),           // 0: grpc.IngestRequest
	(*IngestResponse)(nil),          // 1: grpc.IngestResponse
	(*GetDashboardRequest)(nil),     // 2: grpc.GetDashboardRequest
	(*OverviewMetrics)(nil),         // 3: grpc.OverviewMetrics
	(*ActivityItem)(nil),            // 4: grpc.ActivityItem
	(*TopTeam)(nil),                 // 5: grpc.TopTeam
	(*HourlyStats)(nil),             // 6: grpc.HourlyStats
	(*TopAuthor)(nil),               // 7: grpc.TopAuthor
	(*GetDashboardResponse)(nil),    // 8: grpc.GetDashboardResponse
	(*GetTeamsRequest)(nil),         // 9: grpc.GetTeamsRequest
	(*Team)(nil),                    // 10: grpc.Team
	(*GetTeamsResponse)(nil),        // 11: grpc.GetTeamsResponse
	(*GetTeamRequest)(nil),          // 12: grpc.GetTeamRequest
	(*GetTeamResponse)(nil),         // 13: grpc.GetTeamResponse
	(*GetTeamOverviewRequest)(nil),  // 14: grpc.GetTeamOverviewRequest
	(*TeamOverview)(nil),            // 15: grpc.TeamOverview
	(*GetTeamOverviewResponse)(nil), // 16: grpc.GetTeamOverviewResponse
}
var file_internal_pkg_grpc_proto_metraly_proto_depIdxs = []int32{
	3,  // 0: grpc.GetDashboardResponse.overview:type_name -> grpc.OverviewMetrics
	4,  // 1: grpc.GetDashboardResponse.activity:type_name -> grpc.ActivityItem
	5,  // 2: grpc.GetDashboardResponse.top_teams:type_name -> grpc.TopTeam
	6,  // 3: grpc.GetDashboardResponse.hourly:type_name -> grpc.HourlyStats
	7,  // 4: grpc.GetDashboardResponse.top_authors:type_name -> grpc.TopAuthor
	10, // 5: grpc.GetTeamsResponse.teams:type_name -> grpc.Team
	15, // 6: grpc.GetTeamOverviewResponse.overview:type_name -> grpc.TeamOverview
	0,  // 7: grpc.EventService.Ingest:input_type -> grpc.IngestRequest
	2,  // 8: grpc.EventService.GetDashboard:input_type -> grpc.GetDashboardRequest
	9,  // 9: grpc.EventService.GetTeams:input_type -> grpc.GetTeamsRequest
	12, // 10: grpc.EventService.GetTeam:input_type -> grpc.GetTeamRequest
	14, // 11: grpc.EventService.GetTeamOverview:input_type -> grpc.GetTeamOverviewRequest
	1,  // 12: grpc.EventService.Ingest:output_type -> grpc.IngestResponse
	8,  // 13: grpc.EventService.GetDashboard:output_type -> grpc.GetDashboardResponse
	11, // 14: grpc.EventService.GetTeams:output_type -> grpc.GetTeamsResponse
	13, // 15: grpc.EventService.GetTeam:output_type -> grpc.GetTeamResponse
	16, // 16: grpc.EventService.GetTeamOverview:output_type -> grpc.GetTeamOverviewResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_pkg_grpc_proto_metraly_proto_init() }
func file_internal_pkg_grpc_proto_metraly_proto_init() {
	if File_internal_pkg_grpc_proto_metraly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_grpc_proto_metraly_proto_rawDesc), len(file_internal_pkg_grpc_proto_metraly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_grpc_proto_metraly_proto_goTypes,
		DependencyIndexes: file_internal_pkg_grpc_proto_metraly_proto_depIdxs,
		MessageInfos:      file_internal_pkg_grpc_proto_metraly_proto_msgTypes,
	}.Build()
	File_internal_pkg_grpc_proto_metraly_proto = out.File
	file_internal_pkg_grpc_proto_metraly_proto_goTypes = nil
	file_internal_pkg_grpc_proto_metraly_proto_depIdxs = nil
}
